<?php

return array(
    'tooltips' => array(
		// settings page
		'sgg-shortcode' => __('This shortcode helps you insert your gallery into post or page content. Just copy it and then paste the shortcode into your post or page body. ', 'sgg')
			. '<a target=\'_blank\' href=\'https://supsystic.com/documentation/add-gallery-site-content\'>https://supsystic.com/documentation/add-gallery-site-content/</a>',
		'sgg-php-code' => __('You may use PHPCode, if you need to insert a gallery shortcode to your php code directly. ', 'sgg')
			. '<a target=\'_blank\' href=\'https://supsystic.com/documentation/add-gallery-site-content\'>https://supsystic.com/documentation/add-gallery-site-content/</a>',
        // Area
		'grid-type' => __('Here you can change your gallery type. ', 'sgg') . '</br><img src=@url/Grid.jpg />',
		'title' => __('Here you can change your gallery name. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/main-settings/\'>https://supsystic.com/documentation/main-settings/</a>',
		'gallery-align' => __('Choose the most suitable gallery alignment for your site design. Gallery may be aligned by center, left or right side of the page. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/main-settings/\'>https://supsystic.com/documentation/main-settings</a>',
        'columns' => __('Number of columns with images on gallery page', 'sgg'),
        'responsive-columns' => __('The number of columns for a given width of the screen. We specify the standard 1200px for medium-sized screens, 768px for the tablets, 320 for mobile. You can change this sizes if you want.', 'sgg'),
		'distance' => __('Here you can set the distance between images in your gallery. This parameter affects both horyzontal and vertical distance.', 'sgg') . '</br><img src=@url/distance_between_photos.jpg />',
        'area-height' => __('Height', 'sgg'),
		'area-width' => __('This option helps you set gallery width in pixels or percents. Note: setting this parameter in percents allows your gallery to adjust to any screen size. ', 'sgg') . '</br><img src=@url/gallery-width.jpg />',
		'full-screen-width' => __('Check this checkbox if you want your gallery to be displayed at full screen width. This option is of no use in Vertical gallery layout. Click the link below to see the example of Full Screen Width gallery. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/example/full-width-gallery-example/\'>https://supsystic.com/example/full-width-gallery-example/</a>',
		'area-padding' => __('Here you may set gallery padding value in pixels. Padding will be the same from both sides of the gallery. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/main-settings/\'>https://supsystic.com/documentation/main-settings/</a>',
		'photo-width' => __('Set your image width in pixels or percents. This option is not available in Horizontal, Mosaic gallery. Note: setting this parameter in percents allows your gallery to adjust to any screen size. ', 'sgg') . '</br><img src=@url/width_bet_photos.jpg>',
		'photo-height' => __('Set your image height in pixels or percents. This option is not available in Vertical gallery. Note: setting this parameter in percents allows your gallery to adjust to any screen size. ', 'sgg') . '</br><img src=@url/height_bet_photos.jpg>',
		'browserUrlTooltipHideFree' => __('If this option is enabled, the links on the images will not be displayed in the browser. Also, it will be impossible to open gallery in popup. In the case you are not sure, please do not enable the option. ', 'sgg'),
		'default-settings' =>__('All new galleries you create after enabling the option will be created with these settings by default (even gallery type). Important! This feature may be enabled only in single gallery at once. ', 'sgg'),
	    // Border
		'border-type' => __('Select border type for your gallery thumbnails. ', 'sgg') . '<p><img src=@url/solid_border.jpg><img src=@url/Dashed_border.jpg></p><p><img src=@url/dotted_border.jpg><img src=@url/double_border.jpg></p>',
		'border-type-popup' => __('Select border type for your popup thumbnails. ', 'sgg') . '<p><img src=@url/solid_border.jpg><img src=@url/Dashed_border.jpg></p><p><img src=@url/dotted_border.jpg><img src=@url/double_border.jpg></p>',
		// 'border-type' => __('Select border type for your gallery thumbnails. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/border-type/\'>https://supsystic.com/documentation/border-type/</a>',
		'border-color' => __('Select border color for your gallery thumbnails.', 'sgg'),
		'border-color-popup' => __('Select border color for your popup thumbnails.', 'sgg'),
		'border-width' =>__('Select border thickness for your gallery thumbnails.', 'sgg'),
		'border-width-popup' =>__('Select border thickness for your popup thumbnails.', 'sgg'),
		'popup-border-enable' =>__('Enable border for your popup. (Work only in 6 theme popup)', 'sgg'),
		'border-radius' => __('Set the radius of corner rounding for your button in pixels. ', 'sgg') . '</br><img src=@url/image-radius.jpg>',
		'cropQuality' => __('Here you may set the quality of your displayed gallery thumbnails in percents. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/main-settings/\'>https://supsystic.com/documentation/main-settings/</a>',
        'display-first-photo' => __('When this option is enabled, only first picture from this gallery will be seen on the website. The other pictures will be seen in the popup window after clicking on the first picture.', 'sgg'),
		'open-by-link' =>__('If this option is enabled, you may insert your gallery short link into 	the content of your page. In this case gallery thumbnails will not be displayed on the page and the gallery will open in pop-up box in the same window after clicking on the link. You may find the detailed instructions here: ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/gallery-by-link-in-popup/\'>https://supsystic.com/documentation/gallery-by-link-in-popup/</a>',
		'social-buttons-project' =>__('Select Social Share Buttons project', 'sgg'),
		'social-sharing' => __('In order to use this option you need to additionally install Social Share Buttons plugin by Supsystic. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/social-sharing/\'>https://supsystic.com/documentation/social-sharing/</a>',
		'gallery-social-sharing' =>__('Enable social share buttons on gallery page', 'sgg'),
		'image-social-sharing' =>__('Enable social share buttons on images', 'sgg'),
		'popup-social-sharing' =>__('Enable  social share buttons in popup images', 'sgg'),

        // Shadow
		'sgg-t-shadow' => __('Enable and customize shadows on the background of your thumbnails. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/shadow/\'>https://supsystic.com/documentation/shadow/</a>',
		'sgg-t-shadow-eff-preset' => __('Choose one of these dramatic shadow effects for your thumbnails.', 'sgg'),
		'when-mouse-is-over' =>__('This option determines whether the shadow thumbnail appears or disappears when mouse is over it.', 'sgg'),
		'overlay-type' =>__('If this option is enabled, all image thumbnails in your gallery will be shadowed.', 'sgg'),
		'shadow-color' => __('Here you may define your shadow color.', 'sgg'),
		'shadow-blur' =>__('Here you may set the shadow blur in percents. Note: if \'Overlay image with shadow\' option is enabled, your thumbnails may become blurry.', 'sgg'),
		'shadow-x' =>__('Shadow shifting along X axis.', 'sgg'),
		'shadow-y' =>__('Shadow shifting along Y axis.', 'sgg'),
		//popup
		'box' => __('Customize your pop-up image settings. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/pop-up-image/\'>https://supsystic.com/documentation/pop-up-image/</a>',
		'sgg-t-popup-theme' => __('Choose the most attractive and convenient theme for your pop-up box. Note: \'Linked images\' option works only with Theme #7.', 'sgg'),
		'mobile' =>__('If this option is enabled, your pop-up box will not show up on mobile devices.', 'sgg'),
		'popup-image-text' =>__('Here you may select the type of text that will be displayed in your popup box.', 'sgg'),
		'captions' =>__('If this option is enabled, your captions will not be displayed in pop-up box. ', 'sgg'),
		'hide-long-tooltip-titles' => __('In order to see the whole caption text in popup window you should hover on it and a new semi-transparent box with the whole text will appear. If you don\'t use long texts in captions, just tick this checkbox and extra tooltip in popup will be disabled.', 'sgg'),
		'box-background' => __('Choose color for pop-up page background. ', 'sgg'),
		'box-transparency' => __('Choose pop-up background transparency.', 'sgg'),
		'slideshow' =>__('Enable and customize the slideshow option in your pop-up box.', 'sgg'),
		'sgg-t-popup-slide-show-speed' => __('Set the speed of changing slide in milliseconds.', 'sgg'),
		'popupHoverStop' => __('If this option is enabled, slideshow pauses, when mouse cursor is over image.', 'sgg'),
		'sgg-t-popup-slideshow-autostart' => __('If this option is enabled, slideshow starts automatically. If it is disabled, the play/pause button will appear in left down corner of your pop-up gallery window.', 'sgg'),
		'box-popupsize' => __('Here you may set your pop-up image size.', 'sgg'),
		'box-disableHistory' => __('If this option is enabled, after clicking \'back\' button in your browser, pop-up window will be closed and all image data will be cleared. If disabled - images will be saved in browser history and will be opened again on \'back\' or \'forward\' button click.', 'sgg'),
		'box-disableChangeUrl' => __('If this option is enabled, browser url will not changed.', 'sgg'),

        'popupLinkedImageTextPro' => __('Here you may choose the type of the text, which appears under your linked images after opening them in a pop-up. You may add this text when you choose the linked images from your site media library. Empty text fields will appear at the right side of the page after selecting the image.', 'sgg'),
        'disableSourceImageForLiPro' => __('If this option is enabled, after clicking on the source image thumbnail, only linked images will appear in the pop-up box. The source image itself will not be displayed.', 'sgg'),
        'enableDownloadPhotosButtonPro' => __('If this option is enabled, the Download button will appear in pop-up box, which will allow you to download the original image.', 'sgg'),
        'downloadIconPro' => __('Download icon is available only with Caption Builder', 'sgg'),
        'video.size' => __('Set video size in pop-up box (width x height)', 'sgg'),
        'video.autoplay' => __('If this option is enabled, video playback starts automatically as soon as pop-up box appears.', 'sgg'),
        'video.onEnd' => __('Here you can select, what happens when a video is over.', 'sgg'),
        'customAttributes' => __('Enable and customize custom attributes for filtering and searching.', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/documentation/custom-attributes-filtering-and-searching/\'>read more</a>',
        'additionalCaptionSettingInPro' => __('This option allows you to enable different animated effects for your gallery image thumbnails. The thumbnails will transform when the mouse cursor is over them. Note this option conflicts with some effects (see the list)', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/documentation/thumbnail-transformations/\'>https://supsystic.com/documentation/thumbnail-transformations/</a>',
        'caption-settings-type-pro' => __('Caption builder enables a wide range of options and detailed caption settings. Note: you will not be able to display descriptions of your images if Caption builder will be disabled. ', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/blog/caption-builder-of-photo-gallery/\'>https://supsystic.com/blog/caption-builder-of-photo-gallery/</a>',
        'overlay-effect-image-on-hover-enable' => __('If this effect is enabled, the other image will be shown on the place of the current one, when a mouse cursor is over it. The other image could be selected in the option below (\'Select Image on hover\') and will be shown for all images in this gallery. In case you want to show different pictures, upload them for each image separately on Images List section (\'Hover Caption Image\' tab). Please note, that \'Personal Captions\' option should be enabled', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/example/two-side-images-gallery/\'>https://supsystic.com/example/two-side-images-gallery/</a>',
        'showExifDataPro' => __('This option helps you display image metadata from Exchangeable Image File Format to give your gallery more professional details.', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/example/exif-meta-data/\'>https://supsystic.com/example/exif-meta-data/</a>',
        'chooseIconPro' => __('Choose an icon to indicate that the gallery is loading.', 'sgg') . '</br><img style=\'max-width:200px\' src=@cdn_url_assets/gallery/img/settings/loader.gif />',
        'categoriesPro' => __('This option allows you to arrange your gallery images by categories. It may be useful for galleries with a great number of images.', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/example/categories-gallery-example/\'>https://supsystic.com/example/categories-gallery-example/</a>',
        'paginationPro' => __('This option allows you to split your gallery images to several pages for comfortable navigation. It may be useful for galleries with a great number of images.', 'sgg') . '</br><a target=\'_blank\' href=\'https://supsystic.com/documentation/pagination/\'>https://supsystic.com/documentation/pagination/</a></br></br>' . __('Use a Custom Buttons to establish a personal design for Load More Button, Pagination and Categories Buttons.', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/documentation/custom-buttons/\'>https://supsystic.com/documentation/custom-buttons/</a>',
        'postsLayoutPro' => __('This feature enables post layout for your gallery.', 'sgg') . '</br><a target=\'_blank\' href=\'https://supsystic.com/documentation/posts/\'>https://supsystic.com/documentation/posts/</a>',
        'watermarkPro' => __('This option enables Watermarks.', 'sgg') . '</br><a target=\'_blank\' href=\'https://supsystic.com/documentation/gallery-watermark/\'>https://supsystic.com/documentation/gallery-watermark/</a></br></br>' . __('Use a Custom Buttons to establish a personal design for Load More Button, Pagination and Categories Buttons.', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/documentation/custom-buttons/\'>https://supsystic.com/documentation/custom-buttons/</a>',
		// lazy-load
		'sgg-t-lazyload-enable' => __('This option is important for big galleries. When it is enabled, images are loading gradually as the page scrolls down.', 'sgg'),
		// Gallery Loader
		'preload' =>__('This option enables animated loader to indicate, that images are loading. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/gallery-loader/\'>https://supsystic.com/documentation/gallery-loader/</a>',
		// caption and icons
		'sgg-ci-caption-enable' => __('If this option is enabled, captions are displayed when mouse cursor is over the thumbnail. You may also find detailed caption settings below. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/captions/\'>https://supsystic.com/documentation/captions/</a>',
		'chooseEffect' => __('Choose your captions visual effect. If you are going to enable icons, you need to choose effects with icons. ', 'sgg'),
		'polaroid-effect' => __('If this option is enabled, your gallery image thumbnails will be displayed in Polaroid style frames. Images will be cropped to a square shape. Captions will apperar below the thumbnails when hovering mouse over it. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/polaroid-gallery/\'>https://supsystic.com/documentation/polaroid-gallery/</a>',
		'polaroid-animation' => __('If this option is enabled, your polaroid image thumbnails move when mouse cursor is over them. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/polaroid-gallery/\'>https://supsystic.com/documentation/polaroid-gallery/</a>',
		'polaroid-scattering' => __('Choose this option to make your polaroid image thumbnails scatter in a random way. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/polaroid-gallery/\'>https://supsystic.com/documentation/polaroid-gallery/</a>',
		'polaroid-frame-width' => __('Set polaroid frame padding in pixels. Note: increasing this parameter may make your thumbnail images smaller. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/polaroid-gallery/\'>https://supsystic.com/documentation/polaroid-gallery/</a>',
		'overlay-background' => __('Choose your caption background color.', 'sgg'),
		'overlay-foreground' => __('Choose your caption text color.', 'sgg'),
		'overlay-transparency' => __('Choose your caption background transparency.', 'sgg'),
		'text-size' => __('Set your caption text size.', 'sgg'),
		'text-align' => __('Choose the horizontal align for your caption text.', 'sgg'),
		'overlay-position' => __('Choose the vertical align for your caption text.', 'sgg'),
		'font-family' => __('Choose font family for your caption text.', 'sgg'),
		'tooltip' =>__('If this option is enabled, image title will not appear when mouse cursor is over the image.', 'sgg'),
		'ismobile' =>__('When this option is enabled, caption will be always visible when gallery is displayed on mobile devices.', 'sgg'),
		'photo-icon' =>__('If this option is enabled, icons are displayed when mouse cursor is over the thumbnail. Icons make your gallery interactive and allow your site visitors to take different actions with thumbnails. ', 'sgg') . '</br><img src=@url/icons.jpg />',
		'ci-icons-animation-effects' => __('Here you may choose the animation effects for your icon symbols. Chosen effect will be the same for all the icons.', 'sgg'),
		'ci-icons-color' => __('Choose the color for your icon symbols.', 'sgg'),
		'ci-icons-hover-color' => __('Choose the color for your icon symbols while hovering over them.', 'sgg'),
		'ci-icons-bg-color' => __('Choose the color for your icon backgrounds while hovering over them.', 'sgg'),
		'ci-icons-hover-bg-color' => __('Choose the icon background color transparency.', 'sgg'),
		'ci-icons-hover-size' => __('Here you may set icons size in pixels.', 'sgg'),
		'ci-icons-distance' => __('Set the distance between icons. Note: you may set this parameter only for several icons. ', 'sgg'),
		'ci-icons-show-overlay' => __('This option enables icon background overlay.', 'sgg'),
		'ci-icons-overlay-color' => __('Choose the background overlay color.', 'sgg'),
		'ci-icons-overlay-transparency' => __('Set the value for overlay transparency in percents.', 'sgg'),
		'overlay-personal' => __('If option enabled you can choose personal caption effect per image in images list. If option disabled chosen effect will be used for all images', 'sgg'),
		'overlay-effect-image-on-hover' => __('You may upload an image from Wordpress media library. This image will appear while hovering over any gallery thumbnail.', 'sgg'),
		'isDisableMobileCaption' =>__('When this option is enabled, caption will never be seen when gallery is displayed on mobile devices.', 'sgg'),
        //Categories
        'categories-show' => __('This option allows you to arrange your gallery images by categories. It may be useful for galleries with a great number of images.', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/example/categories-gallery-example/\'>https://supsystic.com/example/categories-gallery-example/</a>',
        'animation-duration' =>__('Transition/animation speed in milliseconds', 'sgg'),
        'enable-shuffling-animation' =>__('Animated sorting and laying out a group of images', 'sgg'),
        //Pagination
        'pages-show' => __('This option allows you to split your gallery images to several pages for comfortable navigation. It may be useful for galleries with a great number of images.', 'sgg') . '</br><a target=\'_blank\' href=\'https://supsystic.com/documentation/pagination/\'>https://supsystic.com/documentation/pagination/</a></br></br>' . __('Use a Custom Buttons to establish a personal design for Load More Button, Pagination and Categories Buttons.', 'sgg') . ' <a target=\'_blank\' href=\'https://supsystic.com/documentation/custom-buttons/\'>https://supsystic.com/documentation/custom-buttons/</a>',
		//Mosaic
        'mosaic-images-count' =>__('Show first images', 'sgg'),
		'mosaic-show-hidden-images' =>__('If this option is enabled, all hidden thumbnails will be displayed below after clicking on thumbnail with count.', 'sgg'),
		// horizontal scroll
		'horizontal-scroll' => __('This option enables horizontal scroll bar for your gallery. You may customize your scroll bar below. Please note, that this option is not available for Mosaic gallery layout. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/horizontal-scroll/\'>https://supsystic.com/documentation/horizontal-scroll/</a>',
		'horizontal-scroll-color' => __('Choose the color of your horizontal scrollbar', 'sgg'),
		'horizontal-scroll-transparency' => __('Choose the transparency of your horizontal scrollbar', 'sgg'),
		'hscroll-mouse-wheel' =>__('You may increase or decrease the mouse scrolling speed for those, who use desktop PC\'s or laptops by changing value of scroll step', 'sgg'),
		'hscroll-touch-gest' =>__('You may increase or decrease the gesture scrolling speed for those, who use the devices with touchscreen by changing value of scroll step', 'sgg'),
		'hScrollResponsiveMode' => __('If this option is enabled, images automatically adjust to the screen size of the mobile device.', 'sgg'),
		// custom buttons
		'custom-buttons-preview' => __('Here you may find a great number of presets to customize your gallery buttons. ', 'sgg') . '<a target=\'_blank\' href=\'https://supsystic.com/documentation/custom-buttons/\'>https://supsystic.com/documentation/custom-buttons/</a>',
    ),
    'tooltips_icon' => array(
        'icon' => 'question'
    ),
);
